name: AWS Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deply to AWS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: python_apis
        IMAGE_TAG: items_api
      run: |
        docker build -t 355633558229.dkr.ecr.eu-west-2.amazonaws.com/image-registry:latest .
        docker push 355633558229.dkr.ecr.eu-west-2.amazonaws.com/image-registry:latest