name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - uses: rickstaa/action-black@v1
    - name: Create Docker network
      run: docker network create docker_network
    - name: Run MongoDb docker image
      run: docker run --docker_network=pg --name mongoDb 
             -p 27017:27017 -d --rm mongo:latest
    - name: Run Tests
      run: |
        make test

